---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: obedur-os
description: This is my personal OS image.

base-image: ghcr.io/blue-build/base-images/fedora-base-nvidia-open
image-version: 43

modules:
  - type: script
    scripts:
      - add-terra.sh
  - type: files
    files:
      - source: system
        destination: /
  
  - type: fonts
    fonts:
      url-fonts:
        - name: MapleMono-NF-CN-unhinted
          url: https://github.com/subframe7536/maple-font/releases/download/v7.9/MapleMono-NF-CN-unhinted.zip

  - type: dnf
    repos:
      copr:
        - atim/starship
        - errornointernet/quickshell
        - zhullyb/v2rayA
        - atim/resources
        - leloubil/wl-clip-persist
        - lemmy/favorites
        - yselkowitz/nwg-shell
    install:
      packages:
        - pam-u2f
        - starship
        - fastfetch
        - tuigreet
        - niri
        - ghostty
        - grim
        - slurp
        - satty
        - wl-clip-persist
        - noctalia-shell
        - kvantum
        - resources
        - mate-polkit
        - nautilus
        - blueman
        - quickshell
        - dae
        - fcitx5-chinese-addons
        - adw-gtk3-theme
        - nwg-look
        - bibata-cursor-theme
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - fuzzel
        - alacritty

  - type: systemd
    system:
      enabled:
        - greetd.service
        - dae.service
  - type: signing
