---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: obedur-os
description: This is my personal OS image.

base-image: ghcr.io/blue-build/base-images/fedora-base-nvidia-open
image-version: 43

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    # remove:
    #   packages:
    #     - firefox
    #     - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        install:
          - io.github.flattool.Warehouse
          - com.github.tchx84.Flatseal

  - type: signing
