---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: obedur-os
description: This is my personal OS image.

base-image: ghcr.io/blue-build/base-images/fedora-base-nvidia-open
image-version: 43

modules:
  - type: os-release
    properties:
      NAME: Obedur-OS
      PRETTY_NAME: Obedur-OS (Powered By BlueBuild)

  - type: kargs
    kargs:
      - rd.luks.options=fido2-device=auto

  - type: script
    scripts:
      - add-terra.sh
      - add-dracut-modules.sh
  - type: files
    files:
      - source: system
        destination: /

  - type: fonts
    fonts:
      url-fonts:
        - name: MapleMono-NF-CN-unhinted
          url: https://github.com/subframe7536/maple-font/releases/download/v7.9/MapleMono-NF-CN-unhinted.zip

  - type: dnf
    repos:
      copr:
        - atim/starship
        - errornointernet/quickshell
        - zhullyb/v2rayA
        - atim/resources
        - leloubil/wl-clip-persist
        - lemmy/favorites
        - yselkowitz/nwg-shell
        - mystical-devil/ReGreet
    install:
      packages:
        - firewalld
        - firewall-config
        - pam-u2f
        - fprintd-pam
        - starship
        - fastfetch
        - ReGreet
        - niri
        - ghostty
        - grim
        - slurp
        - satty
        - wl-clip-persist
        - noctalia-shell
        - kvantum
        - resources
        - mate-polkit
        - nautilus
        - blueman
        - quickshell
        - dae
        - fcitx5-chinese-addons
        - adw-gtk3-theme
        - nwg-look
        - bibata-cursor-theme
        - xdg-user-dirs
        - qt5ct
        - qt6ct
        - steam-devices
        - steam-device-rules
        - seahorse

  - type: dnf
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - fuzzel
        - alacritty
        - nvtop
        - htop
        - swaylock
        - waybar
        - ibus
        - ibus-chewing
        - ibus-setup
        - ibus-gtk3
        - ibus-gtk4
        - ibus-libs

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: user
        install:
          - io.github.flattool.Warehouse
          - com.github.tchx84.Flatseal

  - type: systemd
    system:
      enabled:
        - greetd.service
        - firewalld.service
      masked:
        - systemd-remount-fs.service
  - type: signing
  - type: initramfs
