name: Build ISO - obedur-os-nvidia
on:
  workflow_dispatch:

jobs:
  build-iso:
    name: Build ISO
    runs-on: ubuntu-latest
    steps:
      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          arch: x86_64
          image_name: obedur-os-nvidia
          image_repo: ghcr.io/sorubedo
          image_tag: latest
          version: "44"
          variant: kinoite
          iso_name: obedur-os-nvidia-kinoite-44.iso
          secure_boot_key_url: https://github.com/sorubedo/obedur-os/raw/refs/heads/main/MOK.der
          enrollment_password: obedur

      - name: Upload ISO as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}
            ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
